chore: Sync with upstream

diff --git a/.github/workflows/retry-release.yaml b/.github/workflows/retry-release.yaml
--- a/.github/workflows/retry-release.yaml
+++ b/.github/workflows/retry-release.yaml
@@ -4,34 +4,37 @@ name: Retry Release
 
 on:
   schedule:
-    - cron: "30 5 * * *"
+    - cron: "30 1 * * *"
   workflow_dispatch:
 
 jobs:
-  repository:
-    name: Get Repository Apps
+  apps:
+    name: Get App Inventory
     runs-on: ubuntu-latest
     outputs:
-      apps: ${{ steps.repository.outputs.apps }}
+      apps: ${{ steps.inventory.outputs.apps }}
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Output
-        id: repository
-        run: echo "apps=$(yq eval-all --indent 0 --output-format json '[.]' apps/*/metadata.yaml)" >> $GITHUB_OUTPUT
+      - name: Get App Inventory
+        uses: ./.github/actions/app-inventory
+        id: inventory
 
   retry:
-    if: ${{ needs.repository.outputs.apps != '[]' }}
+    if: ${{ needs.apps.outputs.apps != '[]' }}
     name: Retry Release
     runs-on: ubuntu-latest
-    needs: repository
+    needs: ["apps"]
     strategy:
       matrix:
-        apps: ${{ fromJSON(needs.repository.outputs.apps) }}
+        app: ${{ fromJSON(needs.apps.outputs.apps) }}
       max-parallel: 4
       fail-fast: false
     steps:
+      - name: Checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
       - name: Generate Token
         uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
         id: app-token
@@ -43,28 +46,50 @@ jobs:
         uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
 
       - name: Install regctl
-        uses: regclient/actions/regctl-installer@main
+        uses: regclient/actions/regctl-installer@4d6888fcc4842c9630f60ebc91715a45dd9bd7a3 # main
 
-      - name: Registry Version
+      - name: Get Bake Options
+        id: app-options
+        uses: ./.github/actions/app-options
+        with:
+          app: ${{ matrix.app }}
+
+      - name: Get Container Registry Version
         id: registry
         env:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          if ! version=$(regctl image inspect ghcr.io/heavybullets8/${{ matrix.apps.name }}:rolling \
+          if ! version=$(regctl image inspect ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:rolling \
               | jq --raw-output '.config.Labels["org.opencontainers.image.version"]' 2>/dev/null) || [[ -z "${version}" ]];
           then
-              echo "Failed to get registry version for ${{ matrix.apps.name }}"
+              echo "Failed to get registry version for ${{ matrix.app }}"
               exit 1
           fi
           echo "version=${version}" >> $GITHUB_OUTPUT
 
-      - if: ${{ matrix.apps.version != steps.registry.outputs.version }}
+      - if: ${{ steps.app-options.outputs.version != steps.registry.outputs.version }}
+        name: Find Pull Request
+        uses: juliangruber/find-pull-request-action@48b6133aa6c826f267ebd33aa2d29470f9d9e7d0 # v1.9.0
+        id: find-pull-request
+        with:
+          github-token: ${{ steps.app-token.outputs.token }}
+          labels: app/${{ matrix.app }}
+          state: open
+
+      - if: ${{ steps.find-pull-request.outputs.number != '' }}
         name: Retry Release
         env:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
           gh workflow run release.yaml \
               --repo ${{ github.repository }} \
-              -f app=${{ matrix.apps.name }} \
-              -f release=true \
-              -f test=true
+              -f app=${{ matrix.app }} \
+              -f release=true
+
+          {
+              echo '## Retrying Release'
+              echo
+              echo '| Container Name | Actual Version | Expected Version |'
+              echo '|----------------|------------------|----------------|'
+              echo '| `${{ matrix.app }}` | `${{ steps.registry.outputs.version }}` | `${{ steps.app-options.outputs.version }}` |'
+          } >> $GITHUB_STEP_SUMMARY
